/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as PrivateImport } from './routes/_private'
import { Route as PrivateServicesRouteImport } from './routes/_private/services/route'
import { Route as PrivateReferrerDoctorsRouteImport } from './routes/_private/referrer.doctors/route'
import { Route as PrivateReferrerAgentsRouteImport } from './routes/_private/referrer.agents/route'

// Create Virtual Routes

const PrivateIndexLazyImport = createFileRoute('/_private/')()
const PrivateAddBillLazyImport = createFileRoute('/_private/add-bill')()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const PrivateRoute = PrivateImport.update({
  id: '/_private',
  getParentRoute: () => rootRoute,
} as any)

const PrivateIndexLazyRoute = PrivateIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateRoute,
} as any).lazy(() =>
  import('./routes/_private/index.lazy').then((d) => d.Route),
)

const PrivateAddBillLazyRoute = PrivateAddBillLazyImport.update({
  id: '/add-bill',
  path: '/add-bill',
  getParentRoute: () => PrivateRoute,
} as any).lazy(() =>
  import('./routes/_private/add-bill.lazy').then((d) => d.Route),
)

const PrivateServicesRouteRoute = PrivateServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => PrivateRoute,
} as any).lazy(() =>
  import('./routes/_private/services/route.lazy').then((d) => d.Route),
)

const PrivateReferrerDoctorsRouteRoute =
  PrivateReferrerDoctorsRouteImport.update({
    id: '/referrer/doctors',
    path: '/referrer/doctors',
    getParentRoute: () => PrivateRoute,
  } as any).lazy(() =>
    import('./routes/_private/referrer.doctors/route.lazy').then(
      (d) => d.Route,
    ),
  )

const PrivateReferrerAgentsRouteRoute = PrivateReferrerAgentsRouteImport.update(
  {
    id: '/referrer/agents',
    path: '/referrer/agents',
    getParentRoute: () => PrivateRoute,
  } as any,
).lazy(() =>
  import('./routes/_private/referrer.agents/route.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_private/services': {
      id: '/_private/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof PrivateServicesRouteImport
      parentRoute: typeof PrivateImport
    }
    '/_private/add-bill': {
      id: '/_private/add-bill'
      path: '/add-bill'
      fullPath: '/add-bill'
      preLoaderRoute: typeof PrivateAddBillLazyImport
      parentRoute: typeof PrivateImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexLazyImport
      parentRoute: typeof PrivateImport
    }
    '/_private/referrer/agents': {
      id: '/_private/referrer/agents'
      path: '/referrer/agents'
      fullPath: '/referrer/agents'
      preLoaderRoute: typeof PrivateReferrerAgentsRouteImport
      parentRoute: typeof PrivateImport
    }
    '/_private/referrer/doctors': {
      id: '/_private/referrer/doctors'
      path: '/referrer/doctors'
      fullPath: '/referrer/doctors'
      preLoaderRoute: typeof PrivateReferrerDoctorsRouteImport
      parentRoute: typeof PrivateImport
    }
  }
}

// Create and export the route tree

interface PrivateRouteChildren {
  PrivateServicesRouteRoute: typeof PrivateServicesRouteRoute
  PrivateAddBillLazyRoute: typeof PrivateAddBillLazyRoute
  PrivateIndexLazyRoute: typeof PrivateIndexLazyRoute
  PrivateReferrerAgentsRouteRoute: typeof PrivateReferrerAgentsRouteRoute
  PrivateReferrerDoctorsRouteRoute: typeof PrivateReferrerDoctorsRouteRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateServicesRouteRoute: PrivateServicesRouteRoute,
  PrivateAddBillLazyRoute: PrivateAddBillLazyRoute,
  PrivateIndexLazyRoute: PrivateIndexLazyRoute,
  PrivateReferrerAgentsRouteRoute: PrivateReferrerAgentsRouteRoute,
  PrivateReferrerDoctorsRouteRoute: PrivateReferrerDoctorsRouteRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof PrivateRouteWithChildren
  '/login': typeof LoginRoute
  '/services': typeof PrivateServicesRouteRoute
  '/add-bill': typeof PrivateAddBillLazyRoute
  '/': typeof PrivateIndexLazyRoute
  '/referrer/agents': typeof PrivateReferrerAgentsRouteRoute
  '/referrer/doctors': typeof PrivateReferrerDoctorsRouteRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/services': typeof PrivateServicesRouteRoute
  '/add-bill': typeof PrivateAddBillLazyRoute
  '/': typeof PrivateIndexLazyRoute
  '/referrer/agents': typeof PrivateReferrerAgentsRouteRoute
  '/referrer/doctors': typeof PrivateReferrerDoctorsRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_private': typeof PrivateRouteWithChildren
  '/login': typeof LoginRoute
  '/_private/services': typeof PrivateServicesRouteRoute
  '/_private/add-bill': typeof PrivateAddBillLazyRoute
  '/_private/': typeof PrivateIndexLazyRoute
  '/_private/referrer/agents': typeof PrivateReferrerAgentsRouteRoute
  '/_private/referrer/doctors': typeof PrivateReferrerDoctorsRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/services'
    | '/add-bill'
    | '/'
    | '/referrer/agents'
    | '/referrer/doctors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/services'
    | '/add-bill'
    | '/'
    | '/referrer/agents'
    | '/referrer/doctors'
  id:
    | '__root__'
    | '/_private'
    | '/login'
    | '/_private/services'
    | '/_private/add-bill'
    | '/_private/'
    | '/_private/referrer/agents'
    | '/_private/referrer/doctors'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PrivateRoute: typeof PrivateRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  PrivateRoute: PrivateRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_private",
        "/login"
      ]
    },
    "/_private": {
      "filePath": "_private.tsx",
      "children": [
        "/_private/services",
        "/_private/add-bill",
        "/_private/",
        "/_private/referrer/agents",
        "/_private/referrer/doctors"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_private/services": {
      "filePath": "_private/services/route.tsx",
      "parent": "/_private"
    },
    "/_private/add-bill": {
      "filePath": "_private/add-bill.lazy.tsx",
      "parent": "/_private"
    },
    "/_private/": {
      "filePath": "_private/index.lazy.tsx",
      "parent": "/_private"
    },
    "/_private/referrer/agents": {
      "filePath": "_private/referrer.agents/route.tsx",
      "parent": "/_private"
    },
    "/_private/referrer/doctors": {
      "filePath": "_private/referrer.doctors/route.tsx",
      "parent": "/_private"
    }
  }
}
ROUTE_MANIFEST_END */
